version: '3'

services: 

  #Mysql Service
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    networks: 
      - node-mysql-network

  #Node Service
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    command: node index.js 
    tty: true
    volumes: 
      - ./node:/usr/src/app
    depends_on: 
      - db
    networks: 
      - node-mysql-network
      - node-nginx-network

  #Nginx Service
  nginx:    
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    depends_on: 
      - app
    networks: 
      - node-nginx-network


networks: 
  node-mysql-network:
    driver: bridge   
  node-nginx-network:
    driver: bridge      
